Repository Corn-Market/Corn-Market, pull requests merged in 2022-12, with the labels that each got.

#7 PR : [프론트] 메인, 로그인, 회원가입, 프로필, 동네인증 페이지 화면 구현 #4
  CornMarket/src/main/webapp/WEB-INF/views/base/footer.jsp
  CornMarket/src/main/webapp/WEB-INF/views/base/header.jsp
  CornMarket/src/main/webapp/WEB-INF/views/base/nav.jsp
  CornMarket/src/main/webapp/WEB-INF/views/jsp/test2.jsp
  CornMarket/src/main/webapp/WEB-INF/views/login/login.jsp
  CornMarket/src/main/webapp/WEB-INF/views/main/index.jsp
  CornMarket/src/main/webapp/WEB-INF/views/main/section.jsp
  CornMarket/src/main/webapp/WEB-INF/views/main/section2.jsp
  CornMarket/src/main/webapp/WEB-INF/views/main/section3.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/other_profile_offsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/other_profile_onsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/other_profile_review.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/popup_profile_img.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/popup_profile_update.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/profile_offsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/profile_onsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/profile_review.jsp
  CornMarket/src/main/webapp/WEB-INF/views/signup/signUp.jsp
  CornMarket/src/main/webapp/WEB-INF/views/town/popup_profile_mytown.jsp
  CornMarket/src/main/webapp/resources/css/login/login.css
  CornMarket/src/main/webapp/resources/css/main/index.css
  CornMarket/src/main/webapp/resources/css/main/section.css
  CornMarket/src/main/webapp/resources/css/profile/other_profile.css
  CornMarket/src/main/webapp/resources/css/profile/popup.css
  CornMarket/src/main/webapp/resources/css/profile/popup_img.css
  CornMarket/src/main/webapp/resources/css/profile/popup_update.css
  CornMarket/src/main/webapp/resources/css/profile/profile.css
  CornMarket/src/main/webapp/resources/css/signup/signUp.css
  CornMarket/src/main/webapp/resources/css/town/popup_mytown.css
  CornMarket/src/main/webapp/resources/html/test.html
  CornMarket/src/main/webapp/resources/images/style/KakaoTalk_20221219_090531943.png
  CornMarket/src/main/webapp/resources/images/style/KakaoTalk_20221219_090531943_01.png
  CornMarket/src/main/webapp/resources/images/style/KakaoTalk_20221219_090531943_02.png
  CornMarket/src/main/webapp/resources/images/style/KakaoTalk_20221219_090531943_03.png
  CornMarket/src/main/webapp/resources/images/style/btnG_official.png
  CornMarket/src/main/webapp/resources/images/style/btn_google_signin_light_focus_web@2x.png
  CornMarket/src/main/webapp/resources/images/style/cornmarket.png
  CornMarket/src/main/webapp/resources/images/style/google.png
  CornMarket/src/main/webapp/resources/images/style/kakao_login_large_wide (1).png
  CornMarket/src/main/webapp/resources/images/style/kakao_login_medium_narrow.png
  CornMarket/src/main/webapp/resources/js/login/login.js
  CornMarket/src/main/webapp/resources/js/profile/update_myinfo.js
  CornMarket/src/main/webapp/resources/js/signup/signUp.js
  CornMarket/src/main/webapp/resources/js/town/town.js
Labels: :blue_heart:PR

#9 PR : [프로필] 프로필 조회, 수정 기능과 파일 업로드 API #3
  CornMarket/pom.xml
  CornMarket/src/main/java/com/corn/market/common/api/fileUpload/FileUploadConfig.java
  CornMarket/src/main/java/com/corn/market/common/api/fileUpload/FileUploadService.java
  CornMarket/src/main/java/com/corn/market/common/api/fileUpload/FileUploadTestController.java
  CornMarket/src/main/java/com/corn/market/profile/controller/OtherProfileController.java
  CornMarket/src/main/java/com/corn/market/profile/controller/ProfileController.java
  CornMarket/src/main/java/com/corn/market/profile/dao/ProfileDao.java
  CornMarket/src/main/java/com/corn/market/profile/domain/ProfileReview.java
  CornMarket/src/main/java/com/corn/market/profile/domain/ProfileSale.java
  CornMarket/src/main/java/com/corn/market/profile/domain/ProfileUpdate.java
  CornMarket/src/main/java/com/corn/market/profile/domain/Review.java
  CornMarket/src/main/java/com/corn/market/profile/domain/Sale.java
  CornMarket/src/main/java/com/corn/market/profile/service/ProfileService.java
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/file_upload_test.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/img_test.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/nickname_test.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/other_profile_offsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/other_profile_onsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/other_profile_review.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/popup.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/profile_offsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/profile_onsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/profile_review.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/profile_update.jsp
  CornMarket/src/main/webapp/resources/images/profile/profile_img_default.png
  CornMarket/target/m2e-wtp/web-resources/META-INF/maven/com.corn/market/pom.properties
  CornMarket/target/m2e-wtp/web-resources/META-INF/maven/com.corn/market/pom.xml
Labels: :blue_heart:PR, :deciduous_tree:Back

#10 PR : [동네인증] 동네인증 기능 구현 #5
  .github/PULL_REQUEST_TEMPLATE.md
  CornMarket/src/main/java/com/corn/market/town/controller/TownController.java
  CornMarket/src/main/java/com/corn/market/town/dao/TownDao.java
  CornMarket/src/main/java/com/corn/market/town/domain/TownCertification.java
  CornMarket/src/main/java/com/corn/market/town/domain/TownInfo.java
  CornMarket/src/main/java/com/corn/market/town/service/TownService.java
  CornMarket/src/main/webapp/WEB-INF/views/town_test/popup_profile_mytown.jsp
  CornMarket/src/main/webapp/WEB-INF/views/town_test/test_profile.jsp
  CornMarket/target/m2e-wtp/web-resources/META-INF/maven/com.corn/market/pom.properties
Labels: :blue_heart:PR, :deciduous_tree:Back

#14 PR : [프론트] 아이디 찾기, 비밀번호 찾기 화면과 기능
  CornMarket/src/main/java/com/corn/market/HomeController.java
  CornMarket/src/main/java/com/corn/market/account/api/MailApiController.java
  CornMarket/src/main/java/com/corn/market/account/controller/AccountController.java
  CornMarket/src/main/java/com/corn/market/account/dao/AccountDao.java
  CornMarket/src/main/java/com/corn/market/account/domain/SearchIdMail.java
  CornMarket/src/main/java/com/corn/market/account/domain/SearchPw.java
  CornMarket/src/main/java/com/corn/market/account/service/AccountService.java
  CornMarket/src/main/webapp/WEB-INF/spring/root-context.xml
  CornMarket/src/main/webapp/WEB-INF/views/account/idaccount.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account/idsuccess_popup.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account/joinform.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account/pwaccount.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account/pwsuccess_popup.jsp
  CornMarket/src/main/webapp/WEB-INF/views/main/section.jsp
  CornMarket/src/main/webapp/WEB-INF/views/post/postinfo.jsp
  CornMarket/src/main/webapp/WEB-INF/views/post/postlookup.jsp
  CornMarket/src/main/webapp/WEB-INF/views/post/postmodify.jsp
  CornMarket/src/main/webapp/WEB-INF/views/post/postotherinfo.jsp
  CornMarket/src/main/webapp/WEB-INF/views/post/postregister.jsp
  CornMarket/src/main/webapp/resources/css/account/account.css
  CornMarket/src/main/webapp/resources/css/account/account_popup.css
  CornMarket/src/main/webapp/resources/css/main/section.css
  CornMarket/src/main/webapp/resources/css/post/postinfo.css
  CornMarket/src/main/webapp/resources/css/post/postlookup.css
  CornMarket/src/main/webapp/resources/css/post/postregister.css
  CornMarket/src/main/webapp/resources/images/profile/mascot01.png
  CornMarket/src/main/webapp/resources/images/profile/mascot2.png
  CornMarket/src/main/webapp/resources/images/profile/mascot3.png
  CornMarket/src/main/webapp/resources/images/style/arrow-drop-down.png
  CornMarket/src/main/webapp/resources/js/account/account_id.js
  CornMarket/src/main/webapp/resources/js/account/account_pw.js
  CornMarket/src/main/webapp/resources/js/main/mainslide.js
  CornMarket/src/main/webapp/resources/js/post/postlookup.js
  CornMarket/src/main/webapp/resources/js/post/postregister.js
  CornMarket/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  CornMarket/target/m2e-wtp/web-resources/META-INF/maven/com.corn/market/pom.properties
Labels: :blue_heart:PR, :deciduous_tree:Back, :sunny:Front

#18 PR : 회원가입, 경로 수정
  CornMarket/pom.xml
  CornMarket/src/main/java/com/corn/market/main/controller/MainController.java
  CornMarket/src/main/java/com/corn/market/member/controller/MemberController.java
  CornMarket/src/main/java/com/corn/market/member/dao/MemberDao.java
  CornMarket/src/main/java/com/corn/market/member/domain/Member.java
  CornMarket/src/main/resources/mapper/MemberMapper.xml
  CornMarket/src/main/resources/mybatis-config.xml
  CornMarket/src/main/webapp/WEB-INF/spring/root-context.xml
  CornMarket/src/main/webapp/WEB-INF/views/account/idaccount.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account/joinform.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account/pwaccount.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account_test/id_popup.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account_test/mail_test.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account_test/pw_popup.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account_test/searchid.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account_test/searchpw.jsp
  CornMarket/src/main/webapp/WEB-INF/views/base/header.jsp
  CornMarket/src/main/webapp/WEB-INF/views/base/header_nickname.jsp
  CornMarket/src/main/webapp/WEB-INF/views/chat/chat_list.jsp
  CornMarket/src/main/webapp/WEB-INF/views/chat/popup_chat.jsp
  CornMarket/src/main/webapp/WEB-INF/views/login/login.jsp
  CornMarket/src/main/webapp/WEB-INF/views/main/index.jsp
  CornMarket/src/main/webapp/WEB-INF/views/main/index2.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/other_profile_offsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/other_profile_onsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/other_profile_review.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/popup_profile_img.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/popup_profile_update.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/profile_offsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/profile_onsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/profile_review.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/file_upload_test.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/img_test.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/nickname_test.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/other_profile_offsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/other_profile_onsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/other_profile_review.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/popup.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/profile_offsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/profile_onsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/profile_review.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile_test/profile_update.jsp
  CornMarket/src/main/webapp/WEB-INF/views/review/popup_review.jsp
  CornMarket/src/main/webapp/WEB-INF/views/signup/signUp.jsp
  CornMarket/src/main/webapp/WEB-INF/views/town/popup_profile_mytown.jsp
  CornMarket/src/main/webapp/WEB-INF/views/town_test/popup_profile_mytown.jsp
  CornMarket/src/main/webapp/resources/css/main/footer.css
  CornMarket/src/main/webapp/resources/css/main/header.css
  CornMarket/src/main/webapp/resources/css/main/header_nickname.css
  CornMarket/src/main/webapp/resources/css/review/popup_review.css
  CornMarket/src/main/webapp/resources/js/login/login.js
  CornMarket/src/main/webapp/resources/js/signup/signUp.js
  CornMarket/target/classes/mapper/MemberMapper.xml
  CornMarket/target/classes/mybatis-config.xml
  CornMarket/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  CornMarket/target/m2e-wtp/web-resources/META-INF/maven/com.corn/market/pom.properties
  CornMarket/target/m2e-wtp/web-resources/META-INF/maven/com.corn/market/pom.xml
Labels: :blue_heart:PR

#20 PR : [채팅] 채팅 기능 구현
  CornMarket/src/main/java/com/corn/market/chatting/api/ChatWebSocketHandler.java
  CornMarket/src/main/java/com/corn/market/chatting/api/HandlerSample.java
  CornMarket/src/main/java/com/corn/market/chatting/controller/ChattingController.java
  CornMarket/src/main/java/com/corn/market/chatting/dao/ChattingDao.java
  CornMarket/src/main/java/com/corn/market/chatting/domain/ChatUserInfo.java
  CornMarket/src/main/java/com/corn/market/chatting/domain/ChattingContent.java
  CornMarket/src/main/java/com/corn/market/chatting/domain/ChattingContentList.java
  CornMarket/src/main/java/com/corn/market/chatting/domain/ChattingInfo.java
  CornMarket/src/main/java/com/corn/market/chatting/domain/ChattingRoom.java
  CornMarket/src/main/java/com/corn/market/chatting/domain/ChattingRoomDeleteInfo.java
  CornMarket/src/main/java/com/corn/market/chatting/domain/ChattingRoomInfo.java
  CornMarket/src/main/java/com/corn/market/chatting/domain/CheckChattingRoom.java
  CornMarket/src/main/java/com/corn/market/chatting/domain/WebSocketInfo.java
  CornMarket/src/main/java/com/corn/market/chatting/service/ChattingService.java
  CornMarket/src/main/java/com/corn/market/review/controller/ReviewController.java
  CornMarket/src/main/java/com/corn/market/review/dao/ReviewDao.java
  CornMarket/src/main/java/com/corn/market/review/domain/ReviewReg.java
  CornMarket/src/main/java/com/corn/market/review/service/ReviewService.java
  CornMarket/src/main/webapp/WEB-INF/spring/websocket_config.xml
  CornMarket/src/main/webapp/WEB-INF/views/chatting/chatting_pop.jsp
  CornMarket/src/main/webapp/WEB-INF/views/chatting/chatting_room_list.jsp
  CornMarket/src/main/webapp/WEB-INF/views/chatting_test/chatting.jsp
  CornMarket/src/main/webapp/WEB-INF/views/chatting_test/chatting_list_sample.jsp
  CornMarket/src/main/webapp/WEB-INF/views/chatting_test/chatting_sample.jsp
  CornMarket/src/main/webapp/WEB-INF/views/chatting_test/popup_chat.jsp
  CornMarket/src/main/webapp/WEB-INF/views/review/popup_review.jsp
  CornMarket/src/main/webapp/WEB-INF/web.xml
  CornMarket/src/main/webapp/resources/chatting_sample2.jsp
  CornMarket/src/main/webapp/resources/css/chatting/chat_list.css
  CornMarket/src/main/webapp/resources/css/chatting/popup_chat.css
  CornMarket/src/main/webapp/resources/css/review/popup_review.css
  CornMarket/src/main/webapp/resources/images/profile/profile_img_default.png
  CornMarket/src/main/webapp/resources/images/style/delete_icon.png
  CornMarket/src/main/webapp/resources/js/chatting/chatting_list.js
  CornMarket/src/main/webapp/resources/js/chatting/chatting_pop.js
  CornMarket/src/main/webapp/resources/js/chatting/chatting_sample.js
  CornMarket/src/main/webapp/resources/js/chatting/chatting_sample_list.js
  CornMarket/src/main/webapp/resources/js/review/review.js
  CornMarket/target/m2e-wtp/web-resources/META-INF/maven/com.corn/market/pom.properties
Labels: :blue_heart:PR

#21 PR : 데이터 view 연결
  CornMarket/src/main/java/com/corn/market/board/controller/BoardController.java
  CornMarket/src/main/java/com/corn/market/board/dao/BoardDao.java
  CornMarket/src/main/java/com/corn/market/board/domain/BoardVO.java
  CornMarket/src/main/java/com/corn/market/chatting/controller/ChattingController.java
  CornMarket/src/main/java/com/corn/market/member/controller/MemberController.java
  CornMarket/src/main/java/com/corn/market/profile/controller/ProfileController.java
  CornMarket/src/main/java/com/corn/market/town/controller/TownController.java
  CornMarket/src/main/resources/mapper/BoardMapper.xml
  CornMarket/src/main/webapp/WEB-INF/spring/root-context.xml
  CornMarket/src/main/webapp/WEB-INF/views/account/idaccount.jsp
  CornMarket/src/main/webapp/WEB-INF/views/account/pwaccount.jsp
  CornMarket/src/main/webapp/WEB-INF/views/base/header.jsp
  CornMarket/src/main/webapp/WEB-INF/views/base/header_nickname.jsp
  CornMarket/src/main/webapp/WEB-INF/views/base/nav.jsp
  CornMarket/src/main/webapp/WEB-INF/views/board/list.jsp
  CornMarket/src/main/webapp/WEB-INF/views/board/listPage.jsp
  CornMarket/src/main/webapp/WEB-INF/views/board/listPageSearch.jsp
  CornMarket/src/main/webapp/WEB-INF/views/board/modify.jsp
  CornMarket/src/main/webapp/WEB-INF/views/board/view.jsp
  CornMarket/src/main/webapp/WEB-INF/views/board/write.jsp
  CornMarket/src/main/webapp/WEB-INF/views/chatting/chatting_pop.jsp
  CornMarket/src/main/webapp/WEB-INF/views/login/login.jsp
  CornMarket/src/main/webapp/WEB-INF/views/main/index.jsp
  CornMarket/src/main/webapp/WEB-INF/views/main/sectionagain.jsp
  CornMarket/src/main/webapp/WEB-INF/views/post/postinfo.jsp
  CornMarket/src/main/webapp/WEB-INF/views/post/postlookup.jsp
  CornMarket/src/main/webapp/WEB-INF/views/post/postmodify.jsp
  CornMarket/src/main/webapp/WEB-INF/views/post/postotherinfo.jsp
  CornMarket/src/main/webapp/WEB-INF/views/post/postregister.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/other_profile_offsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/other_profile_onsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/other_profile_review.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/profile_offsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/profile_onsale.jsp
  CornMarket/src/main/webapp/WEB-INF/views/profile/profile_review.jsp
  CornMarket/src/main/webapp/WEB-INF/views/signup/signUp.jsp
  CornMarket/src/main/webapp/resources/css/chatting/chat_list.css
  CornMarket/src/main/webapp/resources/css/main/footer.css
  CornMarket/src/main/webapp/resources/css/main/header_nickname.css
  CornMarket/src/main/webapp/resources/css/main/nav.css
  CornMarket/src/main/webapp/resources/css/post/postlookup.css
  CornMarket/src/main/webapp/resources/css/profile/other_profile.css
  CornMarket/src/main/webapp/resources/css/profile/profile.css
  CornMarket/src/main/webapp/resources/js/chatting/chatting_create.js
  CornMarket/src/main/webapp/resources/js/login/login.js
  CornMarket/src/main/webapp/resources/js/post/postlookup.js
  CornMarket/src/main/webapp/resources/js/signup/signUp.js
  CornMarket/target/classes/mapper/BoardMapper.xml
  CornMarket/target/classes/mapper/MemberMapper.xml
  CornMarket/target/classes/mybatis-config.xml
  CornMarket/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  CornMarket/target/m2e-wtp/web-resources/META-INF/maven/com.corn/market/pom.properties
Labels: :blue_heart:PR

#25 PR : 판매글 조회 기능 수정 #24
  CornMarket/src/main/java/com/corn/market/board/controller/BoardController.java
  CornMarket/src/main/java/com/corn/market/board/dao/BoardDao.java
  CornMarket/src/main/java/com/corn/market/board/domain/BoardVO.java
  CornMarket/src/main/java/com/corn/market/post/controller/PostController.java
  CornMarket/src/main/java/com/corn/market/post/dao/PostDao.java
  CornMarket/src/main/java/com/corn/market/post/domain/PostList.java
  CornMarket/src/main/java/com/corn/market/post/domain/PostVO.java
  CornMarket/src/main/java/com/corn/market/post/service/PostService.java
  CornMarket/src/main/resources/mapper/BoardMapper.xml
  CornMarket/src/main/resources/mapper/PostMapper.xml
  CornMarket/src/main/resources/mybatis-config.xml
  CornMarket/target/classes/mapper/BoardMapper.xml
  CornMarket/target/classes/mapper/PostMapper.xml
  CornMarket/target/classes/mybatis-config.xml
  CornMarket/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  CornMarket/target/m2e-wtp/web-resources/META-INF/maven/com.corn/market/pom.properties
Labels: :blue_heart:PR
